### ISSUE TITLE
Schema for SsKey should be  ["string", "null"] and not "String"

### ISSUE THREAD

**Issue by nucklehead** [RackHD/on-tasks#298]
Should use ["string", "null"] instead of "String" for SsKey 
at https://github.com/RackHD/on-tasks/blob/master/lib/task-data/schemas/install-os-types.json#L24

because the InstallExi will fail if rootSsKey is not passed.

IIt will fail with:
error:
10:49:42 http.1   |    stack:
10:49:42 http.1   |      - Error: Task.Os.Install.Esx: JSON schema validation failed - data.rootSshKey should be string
10:49:42 http.1   |      -     at TaskOptionValidator.JsonSchemaValidator.validatePatternsSkipped (/root/RackHD/on-core/lib/common/json-schema-validator.js:86:2…
.......

**Comment by yyscamper** [comment]
@nucklehead : The `rootSshKey` is string, this is expected, `null` is not allowed.  If you don't want to specify the rootSshKey, please don't add it in the workflow options playload.

There is another possibility is that you are using old code, the old code set the default rootSshKey to `null` even if you don't specify it while running workflow, but actually it has been fixed in latest code. To confirm, please attached the log about the real options that passed the install-os job, you can get it from on-taskgraph.log.

**Comment by nucklehead** [comment]
@yyscamper : It is most likely the second case because i did not pass the rootSshKey option. Also how recent is the code you are refering to because I pull the code from master this past Friday.
I will attach the logs in the AM EST.

**Comment by yyscamper** [comment]
@nucklehead : How is the latest status on this issue?

**Comment by nucklehead** [comment]
Hey @yyscamper. Sorry for the late reply. It seems I am no longer running into this issue. I reverted the code back to just string and it worked fine. I think I had to drop my database.

I will close this. Thanks
